name: autoupdate

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  RUNNING_ON_CI: "true"
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

on:
  schedule:
    - cron: '53 03,15 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_PUSH_TOKEN }}
      - name: Cleanup checkout
        run: git fetch --prune --prune-tags
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
          check-latest: true
      - name: Config Git user
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
      - name: Build and push
        run: .github/autoupdate.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
